
version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    privileged: true
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #   - 5432:5432
  #   volumes:
  #     - ./postgresdata:/var/lib/postgresql/data
  #   privileged: true